# Generated by Django 4.2.16 on 2024-12-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_member_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
