# Generated by Django 4.2.16 on 2024-12-14 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeUser',
        ),
    ]
