# Generated by Django 4.2.16 on 2025-02-24 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0003_remove_public_phonenumber_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('mobile', 'موبایل'), ('work', 'اداری'), ('home', 'منزل')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='public_contact',
            old_name='address',
            new_name='latest_editor_log',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='public_contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='latest_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='public_contact',
            index=models.Index(fields=['first_name', 'last_name'], name='contacts_pu_first_n_3d0dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='public_contact',
            index=models.Index(fields=['organization'], name='contacts_pu_organiz_b194dd_idx'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='contacts.public_contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.public_contact'),
        ),
    ]
