# Generated by Django 4.2.16 on 2025-02-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_address_contact_remove_phonenumber_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public_contact',
            old_name='address',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='public_contact',
            old_name='mobile_number',
            new_name='mobile_number_1',
        ),
        migrations.RenameField(
            model_name='public_contact',
            old_name='phone_number',
            new_name='mobile_number_2',
        ),
        migrations.RenameField(
            model_name='public_contact',
            old_name='postal_code',
            new_name='mobile_number_3',
        ),
        migrations.RenameField(
            model_name='public_contact',
            old_name='updated_at',
            new_name='modified_at',
        ),
        migrations.AddField(
            model_name='public_contact',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='address_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='address_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='deleted_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='latest_editor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='latest_editor_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_4_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_1_ex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_1_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_1_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_2_ex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_2_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_3_ex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_3_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_4_ex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_4_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_4_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_5_ex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_5_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_5_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_6_ex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_6_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_6_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='postal_code_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='postal_code_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='postal_code_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='public_contact',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
