# Generated by Django 4.2.16 on 2025-02-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_rename_address_public_contact_address_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_contact',
            name='category_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
