# Generated by Django 4.2.16 on 2025-03-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_alter_public_contact_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public_contact',
            old_name='email',
            new_name='mobile_number_1_email',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='contact_person_mobile',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='contact_person_name',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='manager_mobile',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='telefax',
        ),
        migrations.RemoveField(
            model_name='public_contact',
            name='title',
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_3_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='mobile_number_4_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_1_organizational_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_2_organizational_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_3_organizational_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_4_organizational_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_5_organizational_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='public_contact',
            name='phone_number_6_organizational_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
